name: test
on: [push]
jobs:
  run-exercise-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install packages
        run: yarn install
      - name: test exercises
        run: yarn test exercise
